server:
  port: 8084

spring:
  application:
    name: storage-service

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: storage-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.log_system.storage_service.event.Event

  data:
    elasticsearch:
      repositories:
        enabled: true

  elasticsearch:
    uris: http://localhost:9200


logging:
  level:
    org.springframework.data.elasticsearch.client: ERROR